// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAyyzYSJPFBuHUSOmI8zE6LSZLe4sJcHAU',
    appId: '1:912084265308:web:2689b79b4bd6a4bcd07999',
    messagingSenderId: '912084265308',
    projectId: 'groceryee-b0745',
    authDomain: 'groceryee-b0745.firebaseapp.com',
    storageBucket: 'groceryee-b0745.appspot.com',
    measurementId: 'G-CCS9XZWH96',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZmxPL8RgIuoUlgGGV7zagEJA6w0-N9Yg',
    appId: '1:912084265308:android:f55af387142569d1d07999',
    messagingSenderId: '912084265308',
    projectId: 'groceryee-b0745',
    storageBucket: 'groceryee-b0745.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDFvHhNB4gqK1orVAjio01TF4XSQStPozs',
    appId: '1:912084265308:ios:457b140c37afeb55d07999',
    messagingSenderId: '912084265308',
    projectId: 'groceryee-b0745',
    storageBucket: 'groceryee-b0745.appspot.com',
    iosClientId: '912084265308-vq1qkck3qpds35psa61fnpa018chl3sp.apps.googleusercontent.com',
    iosBundleId: 'io.flutter.ultimate.grocery.vendors',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDFvHhNB4gqK1orVAjio01TF4XSQStPozs',
    appId: '1:912084265308:ios:fafdff53d1ea2d9fd07999',
    messagingSenderId: '912084265308',
    projectId: 'groceryee-b0745',
    storageBucket: 'groceryee-b0745.appspot.com',
    iosBundleId: 'io.flutter.ultimate.grocery.vendors.RunnerTests',
  );
}
