/*
  Authors : initappz (Rahul Jograna)
  Website : https://initappz.com/
  App Name : Ultimate Grocery Full App Flutter
  This App Template Source code is licensed as per the
  terms found in the Website https://initappz.com/license
  Copyright and Good Faith Purchasers © 2024-present initappz.
*/
import 'package:get/get.dart';

class LocaleString extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        'en_US': {
          "Profile": "Profile",
          "Edit": "Edit",
          "Products": "Products",
          "Reviews": "Reviews",
          "Change Password": "Change Password",
          "Languages": "Languages",
          "Chats": "Chats",
          "Contact Us": "Contact Us",
          "Faq & Help": "Faq & Help",
          "Privacy And Terms": "Privacy And Terms",
          "About": "About",
          "Logout": "Logout",
          "Frequently Asked Questions": "Frequently Asked Questions",
          "Privacy Policy": "Privacy Policy",
          "About Us": "About Us",
          "Select Category": "Select Category",
          "Select": "Select",
          "Cancel": "Cancel",
          "Full Name": "Full Name",
          "Email Address": "Email Address",
          "Message": "Message",
          "Submit": "Submit",
          "Select Driver": "Select Driver",
          "KM": "KM",
          "Choose From": "Choose From",
          "Gallery": "Gallery",
          "Camera": "Camera",
          "Your store cover image": "Your store cover image",
          "Store Name": "Store Name",
          "Store Address": "Store Address",
          "Select Latitude & Longitude from here :": "Select Latitude & Longitude from here :",
          "Please enter valid Latitude & Longitude otherwise app may not work properly.": "Please enter valid Latitude & Longitude otherwise app may not work properly.",
          "Store Latitude": "Store Latitude",
          "Store Longitude": "Store Longitude",
          "Zipcode": "Zipcode",
          "Description": "Description",
          "Open Time": "Open Time",
          "Close Time": "Close Time",
          "Update": "Update",
          "Connection Failed": "Connection Failed",
          "Could not connect to network,": "Could not connect to network,",
          "Please check and try again.": "Please check and try again.",
          "retry": "retry",
          "Verify your phone number": "Verify your phone number",
          "Message...": "Message...",
          "Fresh fruits and Vegetables": "Fresh fruits and Vegetables",
          "Fresh fruits and vegetables are an important part of a healthy diet. They contain essential vitamins, minerals, fiber and other nutrients that are essential for good health":
              "Fresh fruits and vegetables are an important part of a healthy diet. They contain essential vitamins, minerals, fiber and other nutrients that are essential for good health",
          "Grocery to your door steps": "Grocery to your door steps",
          "We're slowly becoming more aware of how our individual choices can impact our planet. And food - how we consume it and how we shop for it - is one of the most important ways we can make a difference.":
              "We're slowly becoming more aware of how our individual choices can impact our planet. And food - how we consume it and how we shop for it - is one of the most important ways we can make a difference.",
          "Best quality grocery": "Best quality grocery",
          "Best quality product with organic maintenance but with affordable price.": "Best quality product with organic maintenance but with affordable price.",
          "Fastest Delivery": "Fastest Delivery",
          "Free delivery service for highest cart value, without minimum payment.": "Free delivery service for highest cart value, without minimum payment.",
          "Skip": "Skip",
          "Previous": "Previous",
          "Get Started": "Get Started",
          "Next": "Next",
          "Get Orders With Dates": "Get Orders With Dates",
          "Get Results": "Get Results",
          "Total": "Total",
          "Commission": "Commission",
          "Amount Received": "Amount Received",
          "Id": "Id",
          "Order on": "Order on",
          "Items": "Items",
          "Welcome": "Welcome",
          "Please login to your acount": "Please login to your account",
          "Password": "Password",
          "Forgot Password?": "Forgot Password?",
          "Sign In": "Sign In",
          "Want to partner with us ?": "Want to partner with us ?",
          " Join Now": " Join Now",
          "Phone Number": "Phone Number",
          "Send OTP": "Send OTP",
          "Update Product": "Update Product",
          "Create Product": "Create Product",
          "Category": "Category",
          "Sub Category": "Sub Category",
          "Select Sub Category": "Select Sub Category",
          "Product name": "Product name",
          "Product Price": "Product Price",
          "Discount %": "Discount %",
          "Sell Price": "Sell Price",
          "Status": "Status",
          "Available": "Available",
          "Hide": "Hide",
          "In Stock": "In Stock",
          "Out Of Stock": "Out Of Stock",
          "Veg?": "Veg?",
          "Is Single": "Is Single",
          "In Offer": "In Offer",
          "Product Cover": "Product Cover",
          "Upload More Images": "Upload More Images",
          "In Gram": "In Gram",
          "Gram Value": "Gram Value",
          "In KG": "In KG",
          "KG Value": "KG Value",
          "In Liter": "In Liter",
          "Liter Value": "Liter Value",
          "In PCs": "In PCs",
          "PCs Value": "PCs Value",
          "In ML": "In ML",
          "ML Value": "ML Value",
          "Expire Date": "Expire Date",
          "Key Features": "Key Features",
          "Disclaimer": "Disclaimer",
          "Size?": "Size?",
          "Add / Remove": "Add / Remove",
          "Order #": "Order #",
          "Choose Status": "Choose Status",
          "Update Status": "Update Status",
          "Accept": "Accept",
          "Reject": "Reject",
          "Order Cancelled by user": "Order Cancelled by user",
          "Order Delivered": "Order Delivered",
          "Order Rejected": "Order Rejected",
          "Orders": "Orders",
          "Order Item Total": "Order Item Total",
          "Order Delivery Charge": "Order Delivery Charge",
          "Split Order Tax": "Split Order Tax",
          "Split Order Discount": "Split Order Discount",
          "Split Order Wallet Discount": "Split Order Wallet Discount",
          "Amount To Collect": "Amount To Collect",
          "Deliver to": "Deliver to",
          "Basic Detail": "Basic Detail",
          "Order ID": "Order ID",
          "Payment Method": "Payment Method",
          "COD": "COD",
          "PAID": "PAID",
          "Delivery On": "Delivery On",
          "Order Tracking": "Order Tracking",
          "User Information": "User Information",
          "New Orders": "New Orders",
          "Ongoing Orders": "Ongoing Orders",
          "Vendors": "Vendors",
          "ORDER #": "ORDER #",
          " grams": " grams",
          " kg": " kg",
          " ltr": " ltr",
          " ml": " ml",
          " pcs": " pcs",
          "Products Insights": "Products Insights",
          "Search products": "Search products",
          "Register Your Store": "Register Your Store",
          "1": "1",
          "2": "2",
          "3": "3",
          "4": "4",
          "Verify Phone": "Verify Phone",
          "Verify E-Mail": "Verify E-Mail",
          "First Name": "First Name",
          "Last Name": "Last Name",
          "Confirm Password": "Confirm Password",
          "Save Information": "Save Information",
          "Choose City": "Choose City",
          "Select City": "Select City",
          "Register Now": "Register Now",
          "Reset Password": "Reset Password",
          "Please enter your credentials": "Please enter your credentials",
          "New Password": "New Password",
          "Update Password": "Update Password",
          "Received from": "Received from",
          "Search product": "Search product",
          "No Internet Connection": "No Internet Connection",
          "Chart View": "Chart View",
          "Orders Trends": "Orders Trends",
          "Month's distribution of your orders": "Month's distribution of your orders",
          "Menu items": "Menu items",
          "Quantity Sold": "Quantity Sold",
          "Total number of orders today": "Total number of orders today",
          "Total number of orders weekly": "Total number of orders weekly",
          "Total number of orders monthly": "Total number of orders monthly",
          "Business Insights": "Business Insights",
          "Deliverd Orders": "Deliverd Orders",
          "See More": "See More",
          "Today": "Today",
          "This Week :": "This Week :",
          "This Month :": "This Month :",
          "Get more orders from": "Get more orders from",
          "Items with grocery images lead to more orders compared to items without them.Add photos to your menu items to get more orders.":
              "Items with grocery images lead to more orders compared to items without them.Add photos to your menu items to get more orders.",
          "Rejected Orders": "Rejected Orders",
          "Lost sale from orders rejected by you": "Lost sale from orders rejected by you",
          "Improve yourself": "Improve yourself",
          "Great Work!": "Great Work!",
          "You have some rejected and cancelled orders on your current month's stats, this will impact on your future sells, improve your self":
              "You have some rejected and cancelled orders on your current month's stats, this will impact on your future sells, improve your self",
          "You have accepted all orders till now in this month": "",
          "Customer Complaints": "Customer Complaints",
          "Details from": "Details from",
          "Top Items in your menu": "Top Items in your menu",
          "Analytics": "Analytics",
          "Account": "Account",
          "Session expired!": "Session expired!",
          "Please wait": "Please wait",
          "All fields are required": "All fields are required",
          "Email is not valid": "Email is not valid",
          "New Mail Request Received": "New Mail Request Received",
          "You have received new mail": "You have received new mail",
          "New Contact Details": "New Contact Details",
          "We have received your request, we will respond on your issue soon": "We have received your request, we will respond on your issue soon",
          "Alert!": "Alert!",
          "Contact Information Sent": "Contact Information Sent",
          "Okay": "Okay",
          "Cover image required": "Cover image required",
          "Updated": "Updated",
          "Your account is blocked, please contact administrator": "Your account is blocked, please contact administrator",
          "Not valid user": "Not valid user",
          "Something went wrong while signin": "Something went wrong while signin",
          "Something went wrong": "Something went wrong",
          "Phone Number is required": "Phone Number is required",
          "Verification": "Verification",
          "We have sent verification code on": "We have sent verification code on",
          "Verify": "Verify",
          "Please select category": "Please select category",
          "Please select sub category": "Please select sub category",
          "Please enter product price": "Please enter product price",
          "Please enter product description": "Please enter product description",
          "Please enter product name": "Please enter product name",
          "Please add product image": "Please add product image",
          "Product updated": "Product updated",
          "Product created": "Product created",
          "Add item to size": "Add item to size",
          "Add-ons name": "Add-ons name",
          "Add-ons price": "Add-ons price",
          "Add-ons discount price": "Add-ons discount price",
          "Discount must be less than 100": "Discount must be less than 100",
          "Contact": "Contact",
          "Email": "Email",
          "Call": "Call",
          "Are you sure?": "Are you sure?",
          "to Accept this order?": "to Accept this order?",
          "Yes, Accept Order": "Yes, Accept Order",
          "Updating Order": "Updating Order",
          "Status Updated": "Status Updated",
          "to": "to",
          "this order?": "this order?",
          "Yes": "Yes",
          "Order": "Order",
          "Choose status": "Choose status",
          "Ongoing": "Ongoing",
          "Delivered": "Delivered",
          "Contact Number Verified": "Contact Number Verified",
          "Something went wrong while signup": "Something went wrong while signup",
          "Email Verified": "Email Verified",
          "E-mail is required": "E-mail is required",
          "Password mismatch": "Password mismatch",
          "Thanks for your interest in the": "Thanks for your interest in the",
          "Store Register Request Sent": "Store Register Request Sent",
          "Password Updated": "Password Updated",
          "The product arrived too late": "The product arrived too late",
          "The product did not match the description": "The product did not match the description",
          "The purchase was fraudulent": "The purchase was fraudulent",
          "The product was damaged or defective": "The product was damaged or defective",
          "The merchant shipped the wrong item": "The merchant shipped the wrong item",
          "Wrong Item Size or Wrong Product Shipped": "Wrong Item Size or Wrong Product Shipped",
          "Driver arrived too late": "Driver arrived too late",
          "Driver behavior": "Driver behavior",
          "Store Vendors behavior": "Store Vendors behavior",
          "Issue with Payment Amout": "Issue with Payment Amount",
          "Others": "Others",
          "Past Orders": "Past Orders",
          "created": "created",
          "rejected": "rejected",
          "delivered": "delivered",
          "accepted": "accepted",
          "cancelled": "cancelled",
          "ongoing": "ongoing",
          "Home": "Home",
        },
        'hi_IN': {
          "Profile": "प्रोफ़ाइल",
          "Edit": "संपादन करना",
          "Products": "उत्पादों",
          "Reviews": "समीक्षा",
          "Change Password": "पासवर्ड बदलें",
          "Languages": "बोली",
          "Chats": "चैट",
          "Contact Us": "संपर्क करें",
          "Faq & Help": "पूछे जाने वाले प्रश्न और सहायता",
          "Privacy And Terms": "गोपनीयता और शर्तें",
          "About": "के बारे में",
          "Logout": "लॉग आउट",
          "Frequently Asked Questions": "अधिकतर पूछे जाने वाले सवाल",
          "Privacy Policy": "गोपनीयता नीति",
          "About Us": "हमारे बारे में",
          "Select Category": "श्रेणी चुनना",
          "Select": "चुनना",
          "Cancel": "रद्द करना",
          "Full Name": "पूरा नाम",
          "Email Address": "ईमेल पता",
          "Message": "संदेश",
          "Submit": "प्रस्तुत करना",
          "Select Driver": "ड्राइवर का चयन करें",
          "KM": "किमी",
          "Choose From": "से चुनें",
          "Gallery": "गेलरी",
          "Camera": "कैमरा",
          "Your store cover image": "आपके स्टोर की कवर इमेज",
          "Store Name": "स्टोर नाम",
          "Store Address": "स्टोर का पता",
          "Select Latitude & Longitude from here :": "यहां से अक्षांश और देशांतर चुनें:",
          "Please enter valid Latitude & Longitude otherwise app may not work properly.": "कृपया मान्य अक्षांश और देशांतर दर्ज करें अन्यथा ऐप ठीक से काम नहीं कर सकता है।",
          "Store Latitude": "स्टोर अक्षांश",
          "Store Longitude": "स्टोर देशांतर",
          "Zipcode": "पिन कोड",
          "Description": "विवरण",
          "Open Time": "खुला समय",
          "Close Time": "बंद होने का समय",
          "Update": "अद्यतन",
          "Connection Failed": "कनेक्शन विफल",
          "Could not connect to network,": "नेटवर्क से कनेक्ट नहीं हो सका,",
          "Please check and try again.": "कृपया जाँच करें और पुनः प्रयास करें।",
          "retry": "पुन: प्रयास करें",
          "Verify your phone number": "अपना फोन नम्बर सत्यापित करें",
          "Message...": "संदेश...",
          "Fresh fruits and Vegetables": "ताजे फल और सब्जियां",
          "Fresh fruits and vegetables are an important part of a healthy diet. They contain essential vitamins, minerals, fiber and other nutrients that are essential for good health":
              "ताजे फल और सब्जियां स्वस्थ आहार का एक महत्वपूर्ण हिस्सा हैं। इनमें आवश्यक विटामिन, खनिज, फाइबर और अन्य पोषक तत्व होते हैं जो अच्छे स्वास्थ्य के लिए आवश्यक हैं",
          "Grocery to your door steps": "आपके दरवाजे तक किराना",
          "We're slowly becoming more aware of how our individual choices can impact our planet. And food - how we consume it and how we shop for it - is one of the most important ways we can make a difference.":
              "हम धीरे-धीरे इस बारे में अधिक जागरूक हो रहे हैं कि हमारी व्यक्तिगत पसंद हमारे ग्रह को कैसे प्रभावित कर सकती है। और भोजन - हम इसका उपभोग कैसे करते हैं और हम इसके लिए कैसे खरीदारी करते हैं - यह सबसे महत्वपूर्ण तरीकों में से एक है जिससे हम फर्क कर सकते हैं।",
          "Best quality grocery": "उत्तम गुणवत्ता किराना",
          "Best quality product with organic maintenance but with affordable price.": "जैविक रखरखाव के साथ सर्वोत्तम गुणवत्ता वाला उत्पाद लेकिन सस्ती कीमत के साथ।",
          "Fastest Delivery": "सबसे तेज़ डिलीवरी",
          "Free delivery service for highest cart value, without minimum payment.": "न्यूनतम भुगतान के बिना उच्चतम कार्ट मूल्य के लिए निःशुल्क वितरण सेवा।",
          "Skip": "छोड़ें",
          "Previous": "पिछला",
          "Get Started": "शुरू हो जाओ",
          "Next": "अगला",
          "Get Orders With Dates": "तिथियों के साथ आदेश प्राप्त करें",
          "Get Results": "परिणाम प्राप्त करें",
          "Total": "कुल",
          "Commission": "आयोग",
          "Amount Received": "रकम प्राप्त",
          "Id": "पहचान",
          "Order on": "ऑर्डर करें",
          "Items": "सामान",
          "Welcome": "स्वागत",
          "Please login to your acount": "कृपया अपने खाते लॉग इन करें",
          "Password": "पासवर्ड",
          "Forgot Password?": "पासवर्ड भूल गए?",
          "Sign In": "साइन इन करें",
          "Want to partner with us ?": "हमारे साथ साझेदारी करना चाहते हैं?",
          " Join Now": "अब सम्मिलित हों",
          "Phone Number": "फ़ोन नंबर",
          "Send OTP": "OTP भेजें",
          "Update Product": "उत्पाद अपडेट करें",
          "Create Product": "उत्पाद बनाएं",
          "Category": "श्रेणी",
          "Sub Category": "उप श्रेणी",
          "Select Sub Category": "उप श्रेणी का चयन करें",
          "Product name": "प्रोडक्ट का नाम",
          "Product Price": "उत्पाद की कीमत",
          "Discount %": "छूट %",
          "Sell Price": "विक्रय मूल्य",
          "Status": "दर्जा",
          "Available": "उपलब्ध",
          "Hide": "छिपाना",
          "In Stock": "स्टॉक में",
          "Out Of Stock": "स्टॉक ख़त्म",
          "Veg?": "शाकाहारी?",
          "Is Single": "अकेला है",
          "In Offer": "प्रस्ताव में",
          "Product Cover": "उत्पाद कवर",
          "Upload More Images": "अधिक चित्र अपलोड करें",
          "In Gram": "ग्राम में",
          "Gram Value": "ग्राम मूल्य",
          "In KG": "केजी . में",
          "KG Value": "केजी मूल्य",
          "In Liter": "लीटर में",
          "Liter Value": "लीटर मूल्य",
          "In PCs": "पीसी में",
          "PCs Value": "पीसी मूल्य",
          "In ML": "एमएल . में",
          "ML Value": "एमएल मूल्य",
          "Expire Date": "समाप्त होने की तिथि",
          "Key Features": "प्रमुख विशेषताऐं",
          "Disclaimer": "अस्वीकरण",
          "Size?": "आकार?",
          "Add / Remove": "जोड़ना / हटाना",
          "Order #": "आदेश #",
          "Choose Status": "स्थिति चुनें",
          "Update Status": "नवीनतम स्थिति",
          "Accept": "स्वीकार करना",
          "Reject": "अस्वीकार",
          "Order Cancelled by user": "उपयोगकर्ता द्वारा रद्द किया गया आदेश",
          "Order Delivered": "आदेश दिया गया",
          "Order Rejected": "आदेश अस्वीकृत",
          "Orders": "आदेश",
          "Order Item Total": "ऑर्डर आइटम कुल",
          "Order Delivery Charge": "ऑर्डर डिलीवरी चार्ज",
          "Split Order Tax": "स्प्लिट ऑर्डर टैक्स",
          "Split Order Discount": "स्प्लिट ऑर्डर डिस्काउंट",
          "Split Order Wallet Discount": "स्प्लिट ऑर्डर वॉलेट डिस्काउंट",
          "Amount To Collect": "इकट्ठा करने के लिए राशि",
          "Deliver to": "उसे देदो",
          "Basic Detail": "मूल विवरण",
          "Order ID": "आदेश ID",
          "Payment Method": "भुगतान का तरीका",
          "COD": "सीओडी",
          "PAID": "भुगतान किया है",
          "Delivery On": "डिलीवरी चालू",
          "Order Tracking": "आदेश ट्रैकिंग",
          "User Information": "उपयोगकर्ता के लिए जानकारी",
          "New Orders": "नए आदेश",
          "Ongoing Orders": "चल रहे आदेश",
          "Vendors": "विक्रेताओं",
          "ORDER #": "गण #",
          " grams": " ग्राम",
          " kg": " किलोग्राम",
          " ltr": " लीटर",
          " ml": " एमएल",
          " pcs": " पीसीएस",
          "Products Insights": "उत्पाद अंतर्दृष्टि",
          "Search products": "उत्पादों को खोजना",
          "Register Your Store": "अपना स्टोर पंजीकृत करें",
          "1": "1",
          "2": "2",
          "3": "3",
          "4": "4",
          "Verify Phone": "फ़ोन सत्यापित करें",
          "Verify E-Mail": "ईमेल सत्यापित करें",
          "First Name": "पहला नाम",
          "Last Name": "उपनाम",
          "Confirm Password": "पासवर्ड की पुष्टि कीजिये",
          "Save Information": "जानकारी सहेजें",
          "Choose City": "शहर चुनें",
          "Select City": "शहर चुनें",
          "Register Now": "अभी पंजीकरण करें",
          "Reset Password": "पासवर्ड रीसेट",
          "Please enter your credentials": "कृपया अपनी साख दर्ज करें",
          "New Password": "नया पासवर्ड",
          "Update Password": "पासवर्ड अपडेट करें",
          "Received from": "से प्राप्त किया",
          "Search product": "उत्पाद खोजें",
          "No Internet Connection": "कोई इंटरनेट कनेक्शन नहीं",
          "Chart View": "चार्ट दृश्य",
          "Orders Trends": "आदेश रुझान",
          "Month's distribution of your orders": "आपके आदेशों का महीने का वितरण",
          "Menu items": "विकल्प सूची की चीज़ें",
          "Quantity Sold": "बेचा गया सामान",
          "Total number of orders today": "आज के आदेशों की कुल संख्या",
          "Total number of orders weekly": "साप्ताहिक आदेशों की कुल संख्या",
          "Total number of orders monthly": "मासिक आदेशों की कुल संख्या",
          "Business Insights": "व्यापार अंतर्दृष्टि",
          "Deliverd Orders": "सुपुर्दगी आदेश",
          "See More": "और देखें",
          "Today": "आज",
          "This Week :": "इस सप्ताह :",
          "This Month :": "इस महीने :",
          "Get more orders from": "से अधिक ऑर्डर प्राप्त करें",
          "Items with grocery images lead to more orders compared to items without them.Add photos to your menu items to get more orders.":
              "किराने की छवियों वाले आइटम उनके बिना आइटम की तुलना में अधिक ऑर्डर देते हैं। अधिक ऑर्डर प्राप्त करने के लिए अपने मेनू आइटम में फ़ोटो जोड़ें।",
          "Rejected Orders": "अस्वीकृत आदेश",
          "Lost sale from orders rejected by you": "आपके द्वारा अस्वीकृत आदेशों से बिक्री का नुकसान",
          "Improve yourself": "आपने आप को सुधारो",
          "Great Work!": "महान काम!",
          "You have some rejected and cancelled orders on your current month's stats, this will impact on your future sells, improve your self":
              "आपके चालू माह के आँकड़ों पर आपके कुछ अस्वीकृत और रद्द किए गए आदेश हैं, यह आपके भविष्य की बिक्री पर प्रभाव डालेगा, अपने आप में सुधार करेगा",
          "You have accepted all orders till now in this month": "आपने इस महीने में अब तक के सभी आदेश स्वीकार कर लिए हैं",
          "Customer Complaints": "ग्राहकों की शिकायतें",
          "Details from": "से विवरण",
          "Top Items in your menu": "आपके मेनू में शीर्ष आइटम",
          "Analytics": "एनालिटिक्स",
          "Account": "खाता",
          "Session expired!": "सत्र समाप्त हुआ!",
          "Please wait": "कृपया प्रतीक्षा करें",
          "All fields are required": "सभी फ़ील्ड आवश्यक हैं",
          "Email is not valid": "विद्युतडाक मान्य नहीं है",
          "New Mail Request Received": "नया मेल अनुरोध प्राप्त हुआ",
          "You have received new mail": "आपको नया मेल प्राप्त हुआ है",
          "New Contact Details": "नया संपर्क विवरण",
          "We have received your request, we will respond on your issue soon": "हमें आपका अनुरोध प्राप्त हो गया है, हम जल्द ही आपके मुद्दे पर प्रतिक्रिया देंगे",
          "Alert!": "चेतावनी!",
          "Contact Information Sent": "संपर्क जानकारी भेजी गई",
          "Okay": "ठीक",
          "Cover image required": "कवर छवि आवश्यक",
          "Updated": "अद्यतन",
          "Your account is blocked, please contact administrator": "आपका खाता अवरुद्ध है, कृपया व्यवस्थापक से संपर्क करें",
          "Not valid user": "मान्य उपयोगकर्ता नहीं है",
          "Something went wrong while signin": "साइन इन करते समय कुछ गलत हुआ",
          "Something went wrong": "कुछ गलत हो गया",
          "Phone Number is required": "फ़ोन नंबर आवश्यक है",
          "Verification": "सत्यापन",
          "We have sent verification code on": "हमने सत्यापन कोड को भेजा है",
          "Verify": "सत्यापित करना",
          "Please select category": "कृपया श्रेणी चुनें",
          "Please select sub category": "कृपया उप श्रेणी का चयन करें",
          "Please enter product price": "कृपया उत्पाद की कीमत दर्ज करें",
          "Please enter product description": "कृपया उत्पाद विवरण दर्ज करें",
          "Please enter product name": "कृपया उत्पाद का नाम दर्ज करें",
          "Please add product image": "कृपया उत्पाद छवि जोड़ें",
          "Product updated": "उत्पाद अपडेट किया गया",
          "Product created": "उत्पाद बनाया",
          "Add item to size": "आकार में आइटम जोड़ें",
          "Add-ons name": "ऐड-ऑन नाम",
          "Add-ons price": "ऐड-ऑन मूल्य मूल्य",
          "Add-ons discount price": "ऐड-ऑन छूट मूल्य",
          "Discount must be less than 100": "छूट 100 . से कम होनी चाहिए",
          "Contact": "संपर्क करना",
          "Email": "ईमेल",
          "Call": "बुलाना",
          "Are you sure?": "क्या आपको यकीन है?",
          "to Accept this order?": "इस आदेश को स्वीकार करने के लिए?",
          "Yes, Accept Order": "हाँ, आदेश स्वीकार करें",
          "Updating Order": "अद्यतन आदेश",
          "Status Updated": "स्थिति अपडेट",
          "to": "प्रति",
          "this order?": "यह आदेश?",
          "Yes": "हाँ",
          "Order": "आदेश",
          "Choose status": "स्थिति चुनें",
          "Ongoing": "चल रहे",
          "Delivered": "पहुंचा दिया",
          "Contact Number Verified": "संपर्क नंबर सत्यापित",
          "Something went wrong while signup": "साइनअप करते समय कुछ गलत हुआ",
          "Email Verified": "ईमेल सत्यापित हुआ",
          "E-mail is required": "ईमेल की जरूरत है",
          "Password mismatch": "पासवर्ड का मेल नहीं हुआ",
          "Thanks for your interest in the": "में आपकी रुचि के लिए धन्यवाद",
          "Store Register Request Sent": "स्टोर रजिस्टर अनुरोध भेजा गया",
          "Password Updated": "पासवर्ड अपडेट किया गया",
          "The product arrived too late": "उत्पाद बहुत देर से पहुंचा",
          "The product did not match the description": "उत्पाद विवरण से मेल नहीं खाता",
          "The purchase was fraudulent": "खरीद धोखाधड़ी थी",
          "The product was damaged or defective": "उत्पाद क्षतिग्रस्त या दोषपूर्ण था",
          "The merchant shipped the wrong item": "व्यापारी ने गलत वस्तु भेज दी",
          "Wrong Item Size or Wrong Product Shipped": "गलत आइटम का आकार या गलत उत्पाद भेज दिया गया",
          "Driver arrived too late": "ड्राइवर बहुत देर से पहुंचा",
          "Driver behavior": "चालक व्यवहार",
          "Store Vendors behavior": "स्टोर विक्रेताओं का व्यवहार",
          "Issue with Payment Amout": "भुगतान राशि के साथ समस्या",
          "Others": "अन्य",
          "Past Orders": "पिछले आदेश",
          "created": "बनाया था",
          "rejected": "अस्वीकृत",
          "delivered": "पहुंचा दिया",
          "accepted": "को स्वीकृत",
          "cancelled": "रद्द",
          "ongoing": "चल रहे",
          "Home": "घर",
        },
        'es_DE': {
          "Profile": "Perfil",
          "Edit": "Editar",
          "Products": "Productos",
          "Reviews": "Reseñas",
          "Change Password": "Cambia la contraseña",
          "Languages": "Idiomas",
          "Chats": "charlas",
          "Contact Us": "Contacta con nosotros",
          "Faq & Help": "Preguntas frecuentes y ayuda",
          "Privacy And Terms": "Privacidad y Términos",
          "About": "Sobre",
          "Logout": "Cerrar sesión",
          "Frequently Asked Questions": "Preguntas frecuentes",
          "Privacy Policy": "Política de privacidad",
          "About Us": "Sobre nosotros",
          "Select Category": "selecciona una categoría",
          "Select": "Seleccione",
          "Cancel": "Cancelar",
          "Full Name": "Nombre completo",
          "Email Address": "Dirección de correo electrónico",
          "Message": "Mensaje",
          "Submit": "Enviar",
          "Select Driver": "Seleccionar conductor",
          "KM": "kilómetros",
          "Choose From": "Escoge de",
          "Gallery": "Galería",
          "Camera": "Cámara",
          "Your store cover image": "La imagen de portada de tu tienda",
          "Store Name": "Nombre de la tienda",
          "Store Address": "Dirección de la tienda",
          "Select Latitude & Longitude from here :": "Seleccione Latitud y Longitud desde aquí:",
          "Please enter valid Latitude & Longitude otherwise app may not work properly.":
              "Ingrese una latitud y longitud válidas; de lo contrario, es posible que la aplicación no funcione correctamente.",
          "Store Latitude": "Almacenar latitud",
          "Store Longitude": "Almacenar longitud",
          "Zipcode": "Código postal",
          "Description": "Descripción",
          "Open Time": "tiempo abierto",
          "Close Time": "Hora de cierre",
          "Update": "Actualizar",
          "Connection Failed": "La conexión falló",
          "Could not connect to network,": "No se pudo conectar a la red,",
          "Please check and try again.": "Por favor revisa e intenta de nuevo.",
          "retry": "rever",
          "Verify your phone number": "verifica tu numero de telefono",
          "Message...": "Mensaje...",
          "Fresh fruits and Vegetables": "frutas y verduras frescas",
          "Fresh fruits and vegetables are an important part of a healthy diet. They contain essential vitamins, minerals, fiber and other nutrients that are essential for good health":
              "Las frutas y verduras frescas son una parte importante de una dieta saludable. Contienen vitaminas esenciales, minerales, fibra y otros nutrientes que son esenciales para una buena salud.",
          "Grocery to your door steps": "Comestibles a los pasos de su puerta",
          "We're slowly becoming more aware of how our individual choices can impact our planet. And food - how we consume it and how we shop for it - is one of the most important ways we can make a difference.":
              "Poco a poco nos estamos volviendo más conscientes de cómo nuestras elecciones individuales pueden afectar nuestro planeta. Y la comida, cómo la consumimos y cómo la compramos, es una de las formas más importantes en que podemos marcar la diferencia.",
          "Best quality grocery": "Supermercado de la mejor calidad",
          "Best quality product with organic maintenance but with affordable price.": "Producto de la mejor calidad con mantenimiento orgánico pero con precio asequible.",
          "Fastest Delivery": "Entrega más rápida",
          "Free delivery service for highest cart value, without minimum payment.": "Servicio de entrega gratuito para el valor del carrito más alto, sin pago mínimo.",
          "Skip": "Saltar",
          "Previous": "Previo",
          "Get Started": "Empezar",
          "Next": "Próximo",
          "Get Orders With Dates": "Obtener pedidos con fechas",
          "Get Results": "Tener resultados",
          "Total": "Total",
          "Commission": "Comisión",
          "Amount Received": "Cantidad recibida",
          "Id": "Identificación",
          "Order on": "ordenar en",
          "Items": "Elementos",
          "Welcome": "Bienvenidos",
          "Please login to your acount": "Por favor, ingrese a su cuenta",
          "Password": "Clave",
          "Forgot Password?": "¿Has olvidado tu contraseña?",
          "Sign In": "Registrarse",
          "Want to partner with us ?": "¿Quieres asociarte con nosotros?",
          " Join Now": " Únete ahora",
          "Phone Number": "Número de teléfono",
          "Send OTP": "Enviar OTP",
          "Update Product": "Actualizar producto",
          "Create Product": "Crear producto",
          "Category": "Categoría",
          "Sub Category": "Subcategoría",
          "Select Sub Category": "Seleccionar subcategoría",
          "Product name": "Nombre del producto",
          "Product Price": "Precio del producto",
          "Discount %": "Descuento %",
          "Sell Price": "Precio de venta",
          "Status": "Estado",
          "Available": "Disponible",
          "Hide": "Ocultar",
          "In Stock": "En stock",
          "Out Of Stock": "Agotado",
          "Veg?": "¿Verdura?",
          "Is Single": "Es soltero",
          "In Offer": "En oferta",
          "Product Cover": "Portada del producto",
          "Upload More Images": "Subir más imágenes",
          "In Gram": "en gramo",
          "Gram Value": "valor gramo",
          "In KG": "en kg",
          "KG Value": "Valor en kilogramos",
          "In Liter": "en litro",
          "Liter Value": "Valor de litro",
          "In PCs": "en PC",
          "PCs Value": "Valor de PC",
          "In ML": "En ML",
          "ML Value": "Valor de aprendizaje automático",
          "Expire Date": "Fecha de caducidad",
          "Key Features": "Características clave",
          "Disclaimer": "Descargo de responsabilidad",
          "Size?": "¿Tamaño?",
          "Add / Remove": "Agregar / eliminar",
          "Order #": "Ordenar #",
          "Choose Status": "Elija Estado",
          "Update Status": "Estado de actualización",
          "Accept": "Aceptar",
          "Reject": "Rechazar",
          "Order Cancelled by user": "Orden cancelada por el usuario",
          "Order Delivered": "Pedido entregado",
          "Order Rejected": "Pedido rechazado",
          "Orders": "Pedidos",
          "Order Item Total": "Total del artículo del pedido",
          "Order Delivery Charge": "Cargo por envío del pedido",
          "Split Order Tax": "Impuesto de orden dividida",
          "Split Order Discount": "Descuento de pedido dividido",
          "Split Order Wallet Discount": "Descuento de billetera de pedido dividido",
          "Amount To Collect": "Cantidad a cobrar",
          "Deliver to": "Entregar a",
          "Basic Detail": "Detalle básico",
          "Order ID": "Solicitar ID",
          "Payment Method": "Método de pago",
          "COD": "BACALAO",
          "PAID": "PAGADO",
          "Delivery On": "Entrega en",
          "Order Tracking": "Rastreo de orden",
          "User Information": "informacion del usuario",
          "New Orders": "Nuevos pedidos",
          "Ongoing Orders": "Pedidos en curso",
          "Vendors": "Vendedores",
          "ORDER #": "ORDENAR #",
          " grams": " gramos",
          " kg": " kg",
          " ltr": " litros",
          " ml": " ml",
          " pcs": " piezas",
          "Products Insights": "Perspectivas de productos",
          "Search products": "Buscar Productos",
          "Register Your Store": "Registre su tienda",
          "1": "1",
          "2": "2",
          "3": "3",
          "4": "4",
          "Verify Phone": "Verificar teléfono",
          "Verify E-Mail": "Verificar correo electrónico",
          "First Name": "Primer nombre",
          "Last Name": "Apellido",
          "Confirm Password": "Confirmar contraseña",
          "Save Information": "Guardar información",
          "Choose City": "Elige Ciudad",
          "Select City": "Ciudad selecta",
          "Register Now": "Regístrate ahora",
          "Reset Password": "Restablecer la contraseña",
          "Please enter your credentials": "Por favor ingrese sus credenciales",
          "New Password": "Nueva contraseña",
          "Update Password": "Actualiza contraseña",
          "Received from": "Recibido de",
          "Search product": "Buscar producto",
          "No Internet Connection": "Sin conexión a Internet",
          "Chart View": "Vista de gráfico",
          "Orders Trends": "Tendencias de pedidos",
          "Month's distribution of your orders": "Distribución mensual de sus pedidos",
          "Menu items": "Elementos de menú",
          "Quantity Sold": "Cantidad vendida",
          "Total number of orders today": "Número total de pedidos hoy",
          "Total number of orders weekly": "Número total de pedidos semanales",
          "Total number of orders monthly": "Número total de pedidos mensuales",
          "Business Insights": "Información empresarial",
          "Deliverd Orders": "Pedidos entregados",
          "See More": "Ver más",
          "Today": "Este Dia",
          "This Week :": "Esta semana :",
          "This Month :": "Este mes :",
          "Get more orders from": "Recibe más pedidos de",
          "Items with grocery images lead to more orders compared to items without them.Add photos to your menu items to get more orders.":
              "Los artículos con imágenes de comestibles dan lugar a más pedidos en comparación con los artículos que no las tienen. Agrega fotos a los artículos de tu menú para obtener más pedidos.",
          "Rejected Orders": "Pedidos rechazados",
          "Lost sale from orders rejected by you": "Venta perdida de pedidos rechazados por usted",
          "Improve yourself": "Supérate",
          "Great Work!": "¡Buen trabajo!",
          "You have some rejected and cancelled orders on your current month's stats, this will impact on your future sells, improve your self":
              "Tiene algunos pedidos rechazados y cancelados en las estadísticas de su mes actual, esto tendrá un impacto en sus ventas futuras, mejore usted mismo",
          "You have accepted all orders till now in this month": "Ha aceptado todos los pedidos hasta ahora en este mes",
          "Customer Complaints": "Quejas de clientes",
          "Details from": "Detalles de",
          "Top Items in your menu": "Elementos principales en su menú",
          "Analytics": "Analítica",
          "Account": "Cuenta",
          "Session expired!": "¡Sesión expirada!",
          "Please wait": "Espere por favor",
          "All fields are required": "Todos los campos son obligatorios",
          "Email is not valid": "El correo no es válido",
          "New Mail Request Received": "Nueva solicitud de correo recibida",
          "You have received new mail": "Has recibido correo nuevo",
          "New Contact Details": "Nuevos detalles de contacto",
          "We have received your request, we will respond on your issue soon": "Hemos recibido tu solicitud, pronto responderemos a tu problema.",
          "Alert!": "¡Alerta!",
          "Contact Information Sent": "Información de contacto enviada",
          "Okay": "De acuerdo",
          "Cover image required": "Imagen de portada requerida",
          "Updated": "Actualizado",
          "Your account is blocked, please contact administrator": "Su cuenta está bloqueada, comuníquese con el administrador",
          "Not valid user": "Usuario no válido",
          "Something went wrong while signin": "Algo salió mal al iniciar sesión",
          "Something went wrong": "Algo salió mal",
          "Phone Number is required": "Se requiere número de teléfono",
          "Verification": "Verificación",
          "We have sent verification code on": "Hemos enviado el código de verificación el",
          "Verify": "Verificar",
          "Please select category": "Por favor seleccione categoría",
          "Please select sub category": "Seleccione la subcategoría",
          "Please enter product price": "Por favor ingrese el precio del producto",
          "Please enter product description": "Por favor ingrese la descripción del producto",
          "Please enter product name": "Por favor ingrese el nombre del producto",
          "Please add product image": "Por favor agregue la imagen del producto",
          "Product updated": "Producto actualizado",
          "Product created": "Producto creado",
          "Add item to size": "Agregar artículo al tamaño",
          "Add-ons name": "nombre de los complementos",
          "Add-ons price": "precio precio complementos",
          "Add-ons discount price": "Precio de descuento de complementos",
          "Discount must be less than 100": "El descuento debe ser inferior a 100",
          "Contact": "Contacto",
          "Email": "Correo electrónico",
          "Call": "Llamar",
          "Are you sure?": "Estas seguro",
          "to Accept this order?": "para aceptar este pedido?",
          "Yes, Accept Order": "Sí, aceptar pedido",
          "Updating Order": "Orden de actualización",
          "Status Updated": "Estado actualizado",
          "to": "a",
          "this order?": "¿este orden?",
          "Yes": "Sí",
          "Order": "Ordenar",
          "Choose status": "elegir estado",
          "Ongoing": "En curso",
          "Delivered": "Entregado",
          "Contact Number Verified": "Número de contacto verificado",
          "Something went wrong while signup": "Algo salió mal durante el registro",
          "Email Verified": "Correo Electrónico Verificado",
          "E-mail is required": "Correo electronico es requerido",
          "Password mismatch": "Contraseña no coincide",
          "Thanks for your interest in the": "Gracias por su interés en el",
          "Store Register Request Sent": "Solicitud de registro de tienda enviada",
          "Password Updated": "Contraseña actualiza",
          "The product arrived too late": "El producto llego demasiado tarde",
          "The product did not match the description": "El producto no coincidía con la descripción.",
          "The purchase was fraudulent": "La compra fue fraudulenta",
          "The product was damaged or defective": "El producto estaba dañado o defectuoso",
          "The merchant shipped the wrong item": "El comerciante envió el artículo equivocado.",
          "Wrong Item Size or Wrong Product Shipped": "Tamaño de artículo incorrecto o producto enviado incorrecto",
          "Driver arrived too late": "El conductor llegó demasiado tarde",
          "Driver behavior": "Comportamiento del conductor",
          "Store Vendors behavior": "Store Vendors behavior",
          "Issue with Payment Amout": "Problema con el monto del pago",
          "Others": "Otros",
          "Past Orders": "Pedidos anteriores",
          "created": "creado",
          "rejected": "rechazado",
          "delivered": "entregado",
          "accepted": "aceptado",
          "cancelled": "cancelado",
          "ongoing": "en curso",
          "Home": "Hogar",
        },
        'ar_AE': {
          "Profile": "الملف الشخصي",
          "Edit": "يحرر",
          "Products": "منتجات",
          "Reviews": "المراجعات",
          "Change Password": "غير كلمة السر",
          "Languages": "اللغات",
          "Chats": "الدردشات",
          "Contact Us": "اتصل بنا",
          "Faq & Help": "التعليمات و التعليمات",
          "Privacy And Terms": "الخصوصية والشروط",
          "About": "حول",
          "Logout": "تسجيل خروج",
          "Frequently Asked Questions": "أسئلة مكررة",
          "Privacy Policy": "سياسة الخصوصية",
          "About Us": "معلومات عنا",
          "Select Category": "اختر الفئة",
          "Select": "يختار",
          "Cancel": "يلغي",
          "Full Name": "الاسم الكامل",
          "Email Address": "عنوان البريد الالكترونى",
          "Message": "رسالة",
          "Submit": "يُقدِّم",
          "Select Driver": "حدد السائق",
          "KM": "كم",
          "Choose From": "اختر من",
          "Gallery": "صالة عرض",
          "Camera": "آلة تصوير",
          "Your store cover image": "صورة غلاف متجرك",
          "Store Name": "اسم المتجر",
          "Store Address": "عنوان المتجر",
          "Select Latitude & Longitude from here :": "حدد خط الطول وخط العرض من هنا:",
          "Please enter valid Latitude & Longitude otherwise app may not work properly.": "الرجاء إدخال خط الطول وخط العرض صالحين وإلا فقد لا يعمل التطبيق بشكل صحيح.",
          "Store Latitude": "تخزين خط العرض",
          "Store Longitude": "متجر خط الطول",
          "Zipcode": "الرمز البريدي",
          "Description": "وصف",
          "Open Time": "وقت متاح",
          "Close Time": "وقت الاغلاق",
          "Update": "تحديث",
          "Connection Failed": "فشل الاتصال",
          "Could not connect to network,": "تعذر الاتصال بالشبكة ،",
          "Please check and try again.": "يرجى مراجعة وحاول مرة أخرى.",
          "retry": "أعد المحاولة",
          "Verify your phone number": "اكد على رقم هاتفك او جوالك",
          "Message...": "رسالة...",
          "Fresh fruits and Vegetables": "فواكه وخضروات طازجة",
          "Fresh fruits and vegetables are an important part of a healthy diet. They contain essential vitamins, minerals, fiber and other nutrients that are essential for good health":
              "تعتبر الفواكه والخضروات الطازجة جزءًا مهمًا من النظام الغذائي الصحي. تحتوي على فيتامينات ومعادن وألياف أساسية وعناصر مغذية أخرى ضرورية لصحة جيدة",
          "Grocery to your door steps": "البقالة حتى عتبات بابك",
          "We're slowly becoming more aware of how our individual choices can impact our planet. And food - how we consume it and how we shop for it - is one of the most important ways we can make a difference.":
              "أصبحنا ندرك ببطء أكثر كيف يمكن لخياراتنا الفردية أن تؤثر على كوكبنا. والطعام - كيف نستهلكه وكيف نتسوق له - هو أحد أهم الطرق التي يمكننا من خلالها إحداث فرق.",
          "Best quality grocery": "أفضل بقالة جودة",
          "Best quality product with organic maintenance but with affordable price.": "منتج ذو جودة عالية مع صيانة عضوية ولكن بسعر مناسب.",
          "Fastest Delivery": "أسرع توصيل",
          "Free delivery service for highest cart value, without minimum payment.": "خدمة توصيل مجانية لأعلى قيمة لسلة التسوق ، بدون حد أدنى للدفع.",
          "Skip": "يتخطى",
          "Previous": "سابق",
          "Get Started": "البدء",
          "Next": "التالي",
          "Get Orders With Dates": "احصل على الطلبات مع التمور",
          "Get Results": "الحصول على النتائج",
          "Total": "المجموع",
          "Commission": "عمولة",
          "Amount Received": "تم استلام المبلغ",
          "Id": "هوية شخصية",
          "Order on": "اطلب على",
          "Items": "العناصر",
          "Welcome": "أهلا وسهلا",
          "Please login to your acount": "يرجى تسجيل الدخول إلى حسابك",
          "Password": "كلمة المرور",
          "Forgot Password?": "هل نسيت كلمة السر؟",
          "Sign In": "تسجيل الدخول",
          "Want to partner with us ?": "تريد شريكا معنا ؟",
          " Join Now": "نضم الان",
          "Phone Number": "رقم الهاتف",
          "Send OTP": "أرسل OTP",
          "Update Product": "تحديث المنتج",
          "Create Product": "إنشاء منتج",
          "Category": "فئة",
          "Sub Category": "تصنيف فرعي",
          "Select Sub Category": "حدد فئة فرعية",
          "Product name": "اسم المنتج",
          "Product Price": "سعر المنتج",
          "Discount %": "تخفيض ٪",
          "Sell Price": "سعر البيع",
          "Status": "حالة",
          "Available": "متوفرة",
          "Hide": "يخفي",
          "In Stock": "في الأوراق المالية",
          "Out Of Stock": "إنتهى من المخزن",
          "Veg?": "نباتي؟",
          "Is Single": "هو وحيد",
          "In Offer": "في العرض",
          "Product Cover": "غطاء المنتج",
          "Upload More Images": "تحميل المزيد من الصور",
          "In Gram": "بالجرام",
          "Gram Value": "قيمة الجرام",
          "In KG": "في KG",
          "KG Value": "قيمة KG",
          "In Liter": "باللتر",
          "Liter Value": "قيمة اللتر",
          "In PCs": "في أجهزة الكمبيوتر",
          "PCs Value": "قيمة أجهزة الكمبيوتر",
          "In ML": "في ML",
          "ML Value": "قيمة ML",
          "Expire Date": "تاريخ انتهاء الصلاحية",
          "Key Features": "دلائل الميزات",
          "Disclaimer": "تنصل",
          "Size?": "بحجم؟",
          "Add / Remove": "اضف احذف",
          "Order #": "ترتيب #",
          "Choose Status": "اختر الحالة",
          "Update Status": "تحديث الحالة",
          "Accept": "قبول",
          "Reject": "رفض",
          "Order Cancelled by user": "تم إلغاء الطلب من قبل المستخدم",
          "Order Delivered": "أجل تسليم",
          "Order Rejected": "تم رفض الطلب",
          "Orders": "قائمة الطلبات",
          "Order Item Total": "إجمالي عنصر الطلب",
          "Order Delivery Charge": "رسوم توصيل الطلب",
          "Split Order Tax": "تقسيم ضريبة الطلب",
          "Split Order Discount": "خصم الطلب المقسم",
          "Split Order Wallet Discount": "خصم محفظة الطلب المقسم",
          "Amount To Collect": "المبلغ المطلوب تحصيله",
          "Deliver to": "يسلم إلى",
          "Basic Detail": "التفاصيل الأساسية",
          "Order ID": "رقم التعريف الخاص بالطلب",
          "Payment Method": "طريقة الدفع او السداد",
          "COD": "سمك القد",
          "PAID": "دفع",
          "Delivery On": "التسليم في",
          "Order Tracking": "تتبع الطلب",
          "User Information": "معلومات المستخدم",
          "New Orders": "طلبات جديدة",
          "Ongoing Orders": "الطلبات الجارية",
          "Vendors": "الباعة",
          "ORDER #": "ترتيب #",
          " grams": "جرامات ",
          " kg": "كلغ",
          " ltr": "لتر",
          " ml": "مل",
          " pcs": "جهاز كمبيوتر شخصى",
          "Products Insights": "رؤى المنتجات",
          "Search products": "البحث عن المنتجات",
          "Register Your Store": "سجل متجرك",
          "1": "2",
          "2": "2",
          "3": "3",
          "4": "4",
          "Verify Phone": "تحقق من الهاتف",
          "Verify E-Mail": "التحقق من البريد الإلكتروني",
          "First Name": "الاسم الاول",
          "Last Name": "الكنية",
          "Confirm Password": "تأكيد كلمة المرور",
          "Save Information": "حفظ المعلومات",
          "Choose City": "اختر المدينة",
          "Select City": "اختر مدينة",
          "Register Now": "سجل الان",
          "Reset Password": "إعادة تعيين كلمة المرور",
          "Please enter your credentials": "الرجاء إدخال بيانات الاعتماد الخاصة بك",
          "New Password": "كلمة السر الجديدة",
          "Update Password": "تطوير كلمة السر",
          "Received from": "مستلم من",
          "Search product": "البحث عن المنتج",
          "No Internet Connection": "لا يوجد اتصال بالإنترنت",
          "Chart View": "عرض المخطط",
          "Orders Trends": "اتجاهات الطلبات",
          "Month's distribution of your orders": "توزيع الشهر لأوامرك",
          "Menu items": "عناصر القائمة",
          "Quantity Sold": "الكمية المباعة",
          "Total number of orders today": "العدد الإجمالي للطلبات اليوم",
          "Total number of orders weekly": "العدد الإجمالي للطلبات أسبوعيا",
          "Total number of orders monthly": "إجمالي عدد الطلبات شهريًا",
          "Business Insights": "رؤى الأعمال",
          "Deliverd Orders": "أوامر التسليم",
          "See More": "شاهد المزيد",
          "Today": "اليوم",
          "This Week :": "هذا الاسبوع :",
          "This Month :": "هذا الشهر :",
          "Get more orders from": "احصل على المزيد من الطلبات من",
          "Items with grocery images lead to more orders compared to items without them.Add photos to your menu items to get more orders.":
              "تؤدي العناصر التي تحتوي على صور البقالة إلى المزيد من الطلبات مقارنة بالعناصر التي لا تحتوي عليها. أضف صورًا إلى عناصر القائمة للحصول على المزيد من الطلبات.",
          "Rejected Orders": "الطلبات المرفوضة",
          "Lost sale from orders rejected by you": "خسر بيع من أوامر رفضت من قبلك",
          "Improve yourself": "طور نفسك",
          "Great Work!": "عمل عظيم!",
          "You have some rejected and cancelled orders on your current month's stats, this will impact on your future sells, improve your self":
              "لديك بعض الطلبات المرفوضة والملغاة في إحصائيات الشهر الحالي ، سيؤثر ذلك على عمليات البيع المستقبلية ، وتحسين نفسك",
          "You have accepted all orders till now in this month": "لقد قبلت جميع الطلبات حتى الآن في هذا الشهر",
          "Customer Complaints": "شكاوى الزبون",
          "Details from": "التفاصيل من",
          "Top Items in your menu": "أهم العناصر في قائمتك",
          "Analytics": "تحليلات",
          "Account": "الحساب",
          "Session expired!": "انتهت الجلسة!",
          "Please wait": "أرجو الإنتظار",
          "All fields are required": "جميع الحقول مطلوبة",
          "Email is not valid": "البريد الإلكتروني غير صالح",
          "New Mail Request Received": "تم استلام طلب بريد جديد",
          "You have received new mail": "لقد تلقيت بريدًا جديدًا",
          "New Contact Details": "تفاصيل جهة اتصال جديدة",
          "We have received your request, we will respond on your issue soon": "لقد تلقينا طلبك ، وسنرد على مشكلتك قريبًا",
          "Alert!": "انذار!",
          "Contact Information Sent": "تم إرسال معلومات الاتصال",
          "Okay": "تمام",
          "Cover image required": "صورة الغلاف مطلوبة",
          "Updated": "محدث",
          "Your account is blocked, please contact administrator": "تم حظر حسابك ، يرجى الاتصال بالمسؤول",
          "Not valid user": "مستخدم غير صالح",
          "Something went wrong while signin": "حدث خطأ ما أثناء تسجيل الدخول",
          "Something went wrong": "هناك خطأ ما",
          "Phone Number is required": "رقم الهاتف مطلوب",
          "Verification": "تَحَقّق",
          "We have sent verification code on": "لقد أرسلنا رمز التحقق على",
          "Verify": "يؤكد",
          "Please select category": "الرجاء تحديد الفئة",
          "Please select sub category": "الرجاء تحديد فئة فرعية",
          "Please enter product price": "الرجاء إدخال سعر المنتج",
          "Please enter product description": "الرجاء إدخال وصف المنتج",
          "Please enter product name": "الرجاء إدخال اسم المنتج",
          "Please add product image": "الرجاء إضافة صورة المنتج",
          "Product updated": "تم تحديث المنتج",
          "Product created": "تم إنشاء المنتج",
          "Add item to size": "أضف العنصر إلى الحجم",
          "Add-ons name": "اسم الإضافات",
          "Add-ons price": "سعر الإضافات",
          "Add-ons discount price": "سعر خصم الإضافات",
          "Discount must be less than 100": "يجب أن يكون الخصم أقل من 100",
          "Contact": "اتصال",
          "Email": "البريد الإلكتروني",
          "Call": "مكالمة",
          "Are you sure?": "هل أنت واثق؟",
          "to Accept this order?": "لقبول هذا الطلب؟",
          "Yes, Accept Order": "نعم ، اقبل الطلب",
          "Updating Order": "طلب التحديث",
          "Status Updated": "تم تحديث الحالة",
          "to": "إلى",
          "this order?": "هذا الطلب؟",
          "Yes": "نعم",
          "Order": "ترتيب",
          "Choose status": "اختر الحالة",
          "Ongoing": "جاري التنفيذ",
          "Delivered": "تم التوصيل",
          "Contact Number Verified": "تم التحقق من رقم الاتصال",
          "Something went wrong while signup": "حدث خطأ ما أثناء التسجيل",
          "Email Verified": "تم التحقق من البريد الإلكتروني",
          "E-mail is required": "البريد الالكتروني مطلوب",
          "Password mismatch": "كلمة المرور غير متطابقة",
          "Thanks for your interest in the": "شكرا لاهتمامك في",
          "Store Register Request Sent": "تم إرسال طلب تسجيل المتجر",
          "Password Updated": "تم تحديث كلمة السر",
          "The product arrived too late": "وصل المنتج بعد فوات الأوان",
          "The product did not match the description": "المنتج لا يتطابق مع الوصف",
          "The purchase was fraudulent": "كان الشراء احتياليًا",
          "The product was damaged or defective": "المنتج تالف أو به عيب",
          "The merchant shipped the wrong item": "التاجر شحن العنصر الخطأ",
          "Wrong Item Size or Wrong Product Shipped": "حجم السلعة غير صحيح أو شحن منتج خاطئ",
          "Driver arrived too late": "وصل السائق بعد فوات الأوان",
          "Driver behavior": "سلوك السائق",
          "Store Vendors behavior": "سلوك بائعي المتجر",
          "Issue with Payment Amout": "مشكلة في مبلغ الدفع",
          "Others": "آحرون",
          "Past Orders": "الطلبات السابقة",
          "created": "خلقت",
          "rejected": "مرفوض",
          "delivered": "تم التوصيل",
          "accepted": "وافقت",
          "cancelled": "ألغيت",
          "ongoing": "جاري التنفيذ",
          "Home": "مسكن",
        },
      };
}
